#!/bin/bash

case "$1" in
	grey)
		GREP_COLOR='1;30' grep --color=always $2
		;;
	gray)
		GREP_COLOR='1;30' grep --color=always $2
		;;
	red)
		GREP_COLOR='1;31' grep --color=always $2
		;;
	green)
		GREP_COLOR='1;32' grep --color=always $2
		;;
	yellow)
		GREP_COLOR='1;33' grep --color=always $2
		;;
	blue)
		GREP_COLOR='1;34' grep --color=always $2
		;;
	magenta)
		GREP_COLOR='1;35' grep --color=always $2
		;;
	cyan)
		GREP_COLOR='1;36' grep --color=always $2
		;;
	white)
		GREP_COLOR='1;37' grep --color=always $2
		;;
	*)
		echo $"Usage: $0 {grey|gray|red|green|yellow|blue|magenta|cyan|white} text-to-match"
		exit 1
esac
